Change used gcc version because of compilation error in ubsan.c
Compiling gcc 6.3.0 with gcc 7.2.0 results to error:
gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between
pointer and integer
So I changed used version to 5.4.0 because of that. Probably in future I
will update ct-ng and use gcc 7.2.0 but not now.