README: add note in README about using the bundled libelf on macOS
The `libelf` installed using homebrew doesn't define `EM_RISCV`:
```
/src/machine/programloader.cpp:62:32: error: use of undeclared identifier 'EM_RISCV'
    if (this->hdr.e_machine != EM_RISCV) {
```
It seems to be too old to include it.